AdminPanel/Controllers/AdController.cs
using AdminPanel.Models;
using AdminPanel.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using Spots.Domain;
using Spots.Services.Helpers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;

namespace AdminPanel.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdController : Controller
    {
        private readonly IHttpClientFactory httpClientFactory;

        public AdController(IHttpClientFactory httpClientFactory)
        {
            this.httpClientFactory = httpClientFactory ?? throw new ArgumentNullException(nameof(httpClientFactory));
        }

        #region Index
        public async Task<IActionResult> Index(int pageNumber, string searchQuery)
        {
            ViewData["ad"] = "active";
            ViewData["searchString"] = (string.IsNullOrEmpty(searchQuery)) ? "" : searchQuery;
            if (pageNumber < 1)
            {
                pageNumber = 1;
            }
            var httpClient = httpClientFactory.CreateClient("APIClient");

            var request = new HttpRequestMessage(
                HttpMethod.Get,
                $"/api/ad?pageSize=15&pageNumber={pageNumber}&searchQuery={searchQuery}");

            var response = await httpClient.SendAsync(
                request, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);

            response.EnsureSuccessStatusCode();

            var pagination = response.Headers.GetValues("MVC-Pagination").FirstOrDefault().ToString();

            using (var responseStream = await response.Content.ReadAsStreamAsync())
            {
                var deserializedResponse = await JsonSerializer
                    .DeserializeAsync<DeserializedResponseModel<Ad>>(responseStream);
                var deserializedHeader = JsonSerializer.Deserialize<PaginationHeader>(pagination);
                return View(new AdIndexViewModel(deserializedResponse.Data, deserializedHeader));
            }

        }
        #endregion
        #region Create
        public async Task<IActionResult> CreateAd()
        {
            ViewData["ad"] = "active";
            var vm = new AdEditAndCreateViewModel();
            var httpClient = httpClientFactory.CreateClient("APIClient");
            var request = new HttpRequestMessage(
               HttpMethod.Get,
               $"/api/vendor?includeAll=true");

            var response = await httpClient.SendAsync(
               request, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);

            response.EnsureSuccessStatusCode();
            using (var responseStream = await response.Content.ReadAsStreamAsync())
            {
                var deserializedResponse = await JsonSerializer
                    .DeserializeAsync<DeserializedResponseModel<VendorDomainModel>>(responseStream);
                vm.PopulateSelectList(deserializedResponse.Data);
            }
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> CreateAd(AdEditAndCreateViewModel createAdVM)
        {
            ViewData["ad"] = "active";
            if (!ModelState.IsValid)
            {
                return View(createAdVM);
            }

            var newAd = new AdForCreation()
            {
                Name = createAdVM.Name,
                SortOrder = createAdVM.SortOrder,
                ExternalLink = createAdVM.ExternalLink,
                VendorId = createAdVM.VendorId
            };

            var adImage = createAdVM.Files.FirstOrDefault();

            try
            {
                if (adImage.Length > 0)
                {
                    using (var fileStream = adImage.OpenReadStream())
                    {
                        using (var image = Image.Load(adImage.OpenReadStream()))
                        {
                            image.Mutate(h => h.Resize(900, 300));
                            using (var ms = new MemoryStream())
                            {
                                image.SaveAsJpeg(ms);
                                newAd.File = ms.ToArray();
                            }
                        }
                    }
                }
            }
            catch (Exception e)
            {
                if (e.GetType() == typeof(UnknownImageFormatException))
                {
                    TempData["Type"] = "alert-danger";
                    TempData["CUD"] = true;
                    TempData["Message"] = "Action Failed : Bad Image Format";
                    return RedirectToAction("index");
                }
                if (!(e.GetType() == typeof(NullReferenceException)))
                    throw;
            }

            var serializedNewAd = JsonSerializer.Serialize(newAd);

            var httpClient = httpClientFactory.CreateClient("APIClient");

            var request = new HttpRequestMessage(
                HttpMethod.Post,
                $"/api/ad");

            request.Content = new StringContent(
                serializedNewAd,
                System.Text.Encoding.Unicode,
                "application/json");

            var response = await httpClient.SendAsync(
                request, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);

            response.EnsureSuccessStatusCode();

            TempData["Type"] = "alert-success";
            TempData["CUD"] = true;
            TempData["Message"] = "Ad Created Successfully";
            return RedirectToAction("Index");
        }
        #endregion
        #region Edit
        public async Task<IActionResult> EditAd(Guid id)
        {
            ViewData["ad"] = "active";
            var httpClient = httpClientFactory.CreateClient("APIClient");

            var request = new HttpRequestMessage(
                HttpMethod.Get,
                $"/api/ad/{id}");

            var response = await httpClient.SendAsync(
                request, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);

            response.EnsureSuccessStatusCode();
            var ad = new Ad();
            using (var responseStream = await response.Content.ReadAsStreamAsync())
            {
                var deserializedResponse = await JsonSerializer.
                    DeserializeAsync<DeserializedResponseModel<Ad>>(responseStream);
                ad = deserializedResponse.Data.FirstOrDefault();
            }
            var vm = new AdEditAndCreateViewModel(ad);
            request = new HttpRequestMessage(
               HttpMethod.Get,
               $"/api/vendor?includeAll=true");

            response = await httpClient.SendAsync(
               request, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);

            response.EnsureSuccessStatusCode();
            using (var responseStream = await response.Content.ReadAsStreamAsync())
            {
                var deserializedResponse = await JsonSerializer
                    .DeserializeAsync<DeserializedResponseModel<VendorDomainModel>>(responseStream);
                vm.PopulateSelectList(deserializedResponse.Data);
            }

            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> EditAd(AdEditAndCreateViewModel editAdVM, Guid id)
        {
            ViewData["ad"] = "active";
            if (!ModelState.IsValid)
            {
                return View(editAdVM);
            }
            var editedAd = new AdForCreation()
            {
                Name = editAdVM.Name,
                SortOrder = editAdVM.SortOrder,
                ExternalLink = editAdVM.ExternalLink,
                VendorId = editAdVM.VendorId
                
            };

            var adImage = editAdVM.Files.FirstOrDefault();
            var imageChanged = false;
            try
            {
                if (adImage.Length > 0)
                {
                    imageChanged = true;
                    using (var fileStream = adImage.OpenReadStream())
                    {
                        using (var image = Image.Load(adImage.OpenReadStream()))
                        {
                            image.Mutate(h => h.Resize(900, 300));
                            using (var ms = new MemoryStream())
                            {
                                image.SaveAsJpeg(ms);
                                editedAd.File = ms.ToArray();
                            }
                        }
                    }
                }
            }
            catch (Exception e)
            {
                if (e.GetType() == typeof(UnknownImageFormatException))
                {
                    TempData["Type"] = "alert-danger";
                    TempData["CUD"] = true;
                    TempData["Message"] = "Action Failed : Bad Image Format";
                    return RedirectToAction("index");
                }
                if (!(e.GetType() == typeof(NullReferenceException)))
                    throw;
            }
            // serialize it
            var serializedAdForEdit = JsonSerializer.Serialize(editedAd);

            var httpClient = httpClientFactory.CreateClient("APIClient");

            var request = new HttpRequestMessage(
               HttpMethod.Put,
               $"/api/ad/{id}?imageChanged={imageChanged}");

            request.Content = new StringContent(
               serializedAdForEdit,
               System.Text.Encoding.Unicode,
               "application/json");

            var response = await httpClient.SendAsync(
                request, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);

            response.EnsureSuccessStatusCode();
            TempData["Type"] = "alert-success";

AdminPanel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Responsive admin dashboard">
    <meta name="keywords" content="blank, starter">
    
    <title>Spots</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,300i" rel="stylesheet">

    <!-- Styles -->
    <link href="~/css/core.min.css" rel="stylesheet">
    <link href="~/css/app.min.css" rel="stylesheet">
    <link href="~/css/style.min.css" rel="stylesheet">

    <!-- Favicons -->
    <link rel="shortcut icon" href="~/img/favicon.ico">
    <link rel="icon" href="~/img/icon.png">
</head>

<body>

    <!-- Preloader -->
    <div class="preloader">
        <div class="spinner-dots">
            <span class="dot1"></span>
            <span class="dot2"></span>
            <span class="dot3"></span>
        </div>
    </div>


    <!-- Sidebar -->
    <aside class="sidebar sidebar-icons-right sidebar-icons-boxed sidebar-expand-lg sidebar-color-yellow
           sidebar-dark">
        <header class="sidebar-header" style="background-color: #fff">
            <a class="logo-icon" asp-controller="Dashboard" asp-action="Index"><img src="~/img/spots-logo.png" alt="logo icon"></a>
            <span class="logo">
                <a asp-controller="Dashboard" asp-action="Index"><img src="~/img/logo.png" alt="logo"></a>
            </span>
            <span class="sidebar-toggle-fold "></span>
        </header>

        <nav class="sidebar-navigation">
            <ul class="menu">



                <li class="menu-item @ViewData["home"]">
                    <a class="menu-link" asp-controller="Dashboard" asp-action="Index">
                        <span class="icon fa fa-home"></span>
                        <span class="title">Dashboard</span>
                    </a>
                </li>
                @if (User.IsInRole("Admin"))
                {
                    <li class="menu-item @ViewData["category"]">
                        <a class="menu-link" asp-controller="Category" asp-action="Index">
                            <span class="icon ti-receipt"></span>
                            <span class="title">Category</span>
                        </a>
                    </li>
                }
                <li class="menu-item @ViewData["vendor"]">
                    <a class="menu-link" asp-controller="Vendor" asp-action="Index">
                        <span class="icon fa fa-user"></span>
                        <span class="title">Vendor</span>
                    </a>
                </li>
                
                @if (User.IsInRole("Vendor"))
                {
                    <li class="menu-item @ViewData["media"]">
                        <a class="menu-link" asp-controller="Vendor" asp-action="Media">
                            <span class="icon fa fa-photo"></span>
                            <span class="title">Gallery</span>
                        </a>
                    </li>
                    <li class="menu-item @ViewData["offer"]">
                        <a class="menu-link" asp-controller="Offer" asp-action="ListOffer">
                            <span class="icon fa fa-percent"></span>
                            <span class="title">Offer</span>
                        </a>
                    </li>
                }

                @if (User.IsInRole("Admin"))
                {
                    <li class="menu-item @ViewData["ad"]">
                        <a class="menu-link" asp-controller="Ad" asp-action="Index">
                            <span class="icon fa fa-tv"></span>
                            <span class="title">Ads</span>
                        </a>
                    </li>
                }
                @if (User.IsInRole("Admin"))
                {
                    <li class="menu-item @ViewData["user"]">
                        <a class="menu-link" asp-controller="User" asp-action="Index">
                            <span class="icon fa fa-users"></span>
                            <span class="title">User</span>
                        </a>
                    </li>
                }
                @if (User.IsInRole("Admin"))
                {
                    <li class="menu-item  @ViewData["setting"]">
                        <a class="menu-link" asp-controller="Setting" asp-action="Index">
                            <span class="icon ti-settings"></span>
                            <span class="title">Setting</span>
                        </a>
                    </li>
                }

            </ul>
        </nav>

    </aside>
    <!-- END Sidebar -->
    <!-- Topbar -->
    <header class="topbar">
        <div class="topbar-left">
            <span class="topbar-btn sidebar-toggler"><i>&#9776;</i></span>
        </div>
        <div class="topbar-right">
            @if (User.Identity.IsAuthenticated)
            {
                <a class="btn btn-primary" asp-area="" asp-controller="Dashboard" asp-action="Logout">Logout</a>
            }
        </div>
    </header>
    <!-- END Topbar -->
    <!-- Main container -->

    <!--/.main-content -->
    <main>
        @RenderBody()
        <!-- Footer -->

        <!-- END Footer -->

    </main>
    <!-- END Main container -->
    <!-- Global quickview -->
    <div id="qv-global" class="quickview" data-url="~/data/quickview-global.html">
        <div class="spinner-linear">
            <div class="line"></div>
        </div>
    </div>
    <!-- END Global quickview -->
    <!-- Scripts -->
    <script src="~/js/core.min.js"></script>
    <script src="~/js/app.min.js"></script>
    <script src="~/js/script.min.js"></script>

</body>
</html>

AdminPanel/Views/Shared/_gallery.cshtml
@model AdminPanel.Models.VendorGalleryModel

<div class="col-sm-3 col-lg-3 col-md-3">
    <div class="thumbnail img-thumbnail">
        <img src="@("https://localhost:44308/api/images/"+Model.FileName)" alt="" class="rounded">
        <div class="caption">
            <h3>
                <a asp-controller="Vendor" asp-action="DeleteGallery" 
                   asp-route-id="@Model.Id" asp-route-vendorId="@Model.VendorId"
                   class="btn btn-danger">delete</a>
                @*<span>@Model.Title</span>*@
            </h3>
        </div>
    </div>
</div>